OBJECT_FIELDS = {
    0x01: "oFlags",
    # 0x02, 0: "oDialogResponse",
    # 0x02, 1: "oDialogState",
    0x03: "oUnk94",
    0x04: "oSyncID",
    0x05: "oIntangibleTimer",
    0x06: "oPosX",
    0x07: "oPosY",
    0x08: "oPosZ",
    0x09: "oVelX",
    0x0A: "oVelY",
    0x0B: "oVelZ",
    0x0C: "oForwardVel",
    0x0C: "oForwardVelS32",
    0x0D: "oUnkBC",
    0x0E: "oUnkC0",
    0x0F: "oMoveAnglePitch",
    0x10: "oMoveAngleYaw",
    0x11: "oMoveAngleRoll",
    0x12: "oFaceAnglePitch",
    0x13: "oFaceAngleYaw",
    0x14: "oFaceAngleRoll",
    0x15: "oGraphYOffset",
    0x16: "oActiveParticleFlags",
    0x17: "oGravity",
    0x18: "oFloorHeight",
    0x19: "oMoveFlags",
    0x1A: "oAnimState",
    0x23: "oAngleVelPitch",
    0x24: "oAngleVelYaw",
    0x25: "oAngleVelRoll",
    0x26: "oAnimations",
    0x27: "oHeldState",
    0x28: "oWallHitboxRadius",
    0x29: "oDragStrength",
    0x2A: "oInteractType",
    0x2B: "oInteractStatus",
    0x2C: "oParentRelativePosX",
    0x2D: "oParentRelativePosY",
    0x2E: "oParentRelativePosZ",
    0x2F: "oBehParams2ndByte",
    0x31: "oAction",
    0x32: "oSubAction",
    0x33: "oTimer",
    0x34: "oBounciness",
    0x35: "oDistanceToMario",
    0x36: "oAngleToMario",
    0x37: "oHomeX",
    0x38: "oHomeY",
    0x39: "oHomeZ",
    0x3A: "oFriction",
    0x3B: "oBuoyancy",
    0x3C: "oSoundStateID",
    0x3D: "oOpacity",
    0x3E: "oDamageOrCoinValue",
    0x3F: "oHealth",
    0x40: "oBehParams",
    0x41: "oPrevAction",
    0x42: "oInteractionSubtype",
    0x43: "oCollisionDistance",
    0x44: "oNumLootCoins",
    0x45: "oDrawingDistance",
    0x46: "oRoom",
    0x47: "oSyncDeath",
    0x48: "oUnk1A8",
    0x4B: "oWallAngle",
    # 0x4C, 0: "oFloorType",
    # 0x4C, 1: "oFloorRoom",
    0x4D: "oAngleToHome",
    0x4E: "oFloor",
    0x4F: "oDeathSound",
}

OBJECT_FLAGS = {
    (1 <<  0): "OBJ_FLAG_UPDATE_GFX_POS_AND_ANGLE",
    (1 <<  1): "OBJ_FLAG_MOVE_XZ_USING_FVEL",
    (1 <<  2): "OBJ_FLAG_MOVE_Y_WITH_TERMINAL_VEL",
    (1 <<  3): "OBJ_FLAG_SET_FACE_YAW_TO_MOVE_YAW",
    (1 <<  4): "OBJ_FLAG_SET_FACE_ANGLE_TO_MOVE_ANGLE",
    (1 <<  5): "OBJ_FLAG_0020",
    (1 <<  6): "OBJ_FLAG_COMPUTE_DIST_TO_MARIO",
    (1 <<  7): "OBJ_FLAG_ACTIVE_FROM_AFAR",
    (1 <<  8): "OBJ_FLAG_0100",
    (1 <<  9): "OBJ_FLAG_TRANSFORM_RELATIVE_TO_PARENT",
    (1 << 10): "OBJ_FLAG_HOLDABLE",
    (1 << 11): "OBJ_FLAG_SET_THROW_MATRIX_FROM_TRANSFORM",
    (1 << 12): "OBJ_FLAG_1000",
    (1 << 13): "OBJ_FLAG_COMPUTE_ANGLE_TO_MARIO",
    (1 << 14): "OBJ_FLAG_PERSISTENT_RESPAWN",
    (1 << 15): "OBJ_FLAG_8000",
    (1 << 30): "OBJ_FLAG_30",
}
