DATA_TYPE_NONE              = 0
DATA_TYPE_LIGHT             = DATA_TYPE_NONE + 1
DATA_TYPE_TEXTURE           = DATA_TYPE_LIGHT + 1
DATA_TYPE_VERTEX            = DATA_TYPE_TEXTURE + 1
DATA_TYPE_DISPLAY_LIST      = DATA_TYPE_VERTEX + 1
DATA_TYPE_GEO_LAYOUT        = DATA_TYPE_DISPLAY_LIST + 1
DATA_TYPE_ANIMATION_VALUE   = DATA_TYPE_GEO_LAYOUT + 1
DATA_TYPE_ANIMATION_INDEX   = DATA_TYPE_ANIMATION_VALUE + 1
DATA_TYPE_ANIMATION         = DATA_TYPE_ANIMATION_INDEX + 1
DATA_TYPE_ANIMATION_TABLE   = DATA_TYPE_ANIMATION + 1
DATA_TYPE_GFXDYNCMD         = DATA_TYPE_ANIMATION_TABLE + 1
DATA_TYPE_COLLISION         = DATA_TYPE_GFXDYNCMD + 1
DATA_TYPE_LEVEL_SCRIPT      = DATA_TYPE_COLLISION + 1
DATA_TYPE_MACRO_OBJECT      = DATA_TYPE_LEVEL_SCRIPT + 1
DATA_TYPE_TRAJECTORY        = DATA_TYPE_MACRO_OBJECT + 1
DATA_TYPE_MOVTEX            = DATA_TYPE_TRAJECTORY + 1
DATA_TYPE_MOVTEXQC          = DATA_TYPE_MOVTEX + 1
DATA_TYPE_ROOMS             = DATA_TYPE_MOVTEXQC + 1
DATA_TYPE_LIGHT_T           = DATA_TYPE_ROOMS + 1
DATA_TYPE_AMBIENT_T         = DATA_TYPE_LIGHT_T + 1
DATA_TYPE_TEXTURE_LIST      = DATA_TYPE_AMBIENT_T + 1
DATA_TYPE_TEXTURE_RAW       = DATA_TYPE_TEXTURE_LIST + 1
DATA_TYPE_BEHAVIOR_SCRIPT   = DATA_TYPE_TEXTURE_RAW + 1
DATA_TYPE_UNUSED            = DATA_TYPE_BEHAVIOR_SCRIPT + 1
DATA_TYPE_LIGHT_0           = DATA_TYPE_UNUSED + 1
DATA_TYPE_PRIORITY          = 0xFF

DATA_TYPES_ACTOR = {
    DATA_TYPE_LIGHT: True,
    DATA_TYPE_LIGHT_0: False,
    DATA_TYPE_LIGHT_T: False,
    DATA_TYPE_AMBIENT_T: False,
    DATA_TYPE_TEXTURE: True,
    DATA_TYPE_TEXTURE_LIST: False,
    DATA_TYPE_VERTEX: True,
    DATA_TYPE_DISPLAY_LIST: True,
    DATA_TYPE_GEO_LAYOUT: True,
    DATA_TYPE_ANIMATION: True,
    DATA_TYPE_ANIMATION_TABLE: True,
    DATA_TYPE_GFXDYNCMD: False,
}

DATA_TYPES_TEXTURE = {
    DATA_TYPE_TEXTURE: True,
    DATA_TYPE_TEXTURE_RAW: True,
}

DATA_TYPES_BEHAVIOR = {
    DATA_TYPE_BEHAVIOR_SCRIPT: True,
}

DATA_TYPES_COLLISION = {
    DATA_TYPE_COLLISION: True,
}

DATA_TYPES_LEVEL = {
    DATA_TYPE_LIGHT: True,
    DATA_TYPE_LIGHT_0: True,
    DATA_TYPE_LIGHT_T: True,
    DATA_TYPE_AMBIENT_T: True,
    DATA_TYPE_TEXTURE: True,
    DATA_TYPE_TEXTURE_LIST: True,
    DATA_TYPE_VERTEX: True,
    DATA_TYPE_DISPLAY_LIST: True,
    DATA_TYPE_GEO_LAYOUT: True,
    DATA_TYPE_ANIMATION: True,
    DATA_TYPE_ANIMATION_TABLE: True,
    DATA_TYPE_GFXDYNCMD: False,
    DATA_TYPE_COLLISION: True,
    DATA_TYPE_LEVEL_SCRIPT: True,
    DATA_TYPE_MACRO_OBJECT: True,
    DATA_TYPE_TRAJECTORY: True,
    DATA_TYPE_MOVTEX: True,
    DATA_TYPE_MOVTEXQC: True,
    DATA_TYPE_ROOMS: True,
}
