def C(w: int, pos: int, width: int) -> int: return ((w >> pos) & ((1 << width) - 1))

#
# RSP commands
#

G_NOOP = 0x00
G_SETOTHERMODE_H = 0xe3
G_SETOTHERMODE_L = 0xe2
G_SPNOOP = 0xe0
G_ENDDL = 0xdf
G_DL = 0xde
G_MOVEMEM = 0xdc
G_MOVEWORD = 0xdb
G_MTX = 0xda
G_GEOMETRYMODE = 0xd9
G_POPMTX = 0xd8
G_TEXTURE = 0xd7
G_COPYMEM = 0xd2
G_VTX = 0x01
G_TRI1 = 0x05
G_TRI2 = 0x06

#
# RDP commands
#

G_SETCIMG = 0xff
G_SETZIMG = 0xfe
G_SETTIMG = 0xfd
G_SETCOMBINE = 0xfc
G_SETENVCOLOR = 0xfb
G_SETPRIMCOLOR = 0xfa
G_SETBLENDCOLOR = 0xf9
G_SETFOGCOLOR = 0xf8
G_SETFILLCOLOR = 0xf7
G_FILLRECT = 0xf6
G_SETTILE = 0xf5
G_LOADTILE = 0xf4
G_LOADBLOCK = 0xf3
G_SETTILESIZE = 0xf2
G_LOADTLUT = 0xf0
G_SETSCISSOR = 0xed
G_RDPFULLSYNC = 0xe9
G_RDPTILESYNC = 0xe8
G_RDPPIPESYNC = 0xe7
G_RDPLOADSYNC = 0xe6
G_TEXRECTFLIP = 0xe5
G_TEXRECT = 0xe4

#
# Extended commands
#

G_VTX_EXT = 0x11
G_TRI2_EXT = 0x12

#
# G_SETOTHERMODE_H
#

G_MDSFT_ALPHADITHER = 4
G_MDSFT_RGBDITHER = 6
G_MDSFT_COMBKEY = 8
G_MDSFT_TEXTCONV = 9
G_MDSFT_TEXTFILT = 12
G_MDSFT_TEXTLUT = 14
G_MDSFT_TEXTLOD = 16
G_MDSFT_TEXTDETAIL = 17
G_MDSFT_TEXTPERSP = 19
G_MDSFT_CYCLETYPE = 20
G_MDSFT_PIPELINE = 23

G_SETOTHERMODE_H_SHIFTS = {
    G_MDSFT_ALPHADITHER: {
        "cmd": "gsDPSetAlphaDither",
        "consts": {
            (0 << G_MDSFT_ALPHADITHER): "G_AD_PATTERN",
            (1 << G_MDSFT_ALPHADITHER): "G_AD_NOTPATTERN",
            (2 << G_MDSFT_ALPHADITHER): "G_AD_NOISE",
            (3 << G_MDSFT_ALPHADITHER): "G_AD_DISABLE",
        },
    },
    G_MDSFT_RGBDITHER: {
        "cmd": "gsDPSetColorDither",
        "consts": {
            (0 << G_MDSFT_RGBDITHER): "G_CD_MAGICSQ",
            (1 << G_MDSFT_RGBDITHER): "G_CD_BAYER",
            (2 << G_MDSFT_RGBDITHER): "G_CD_NOISE",
            (3 << G_MDSFT_RGBDITHER): "G_CD_DISABLE",
        },
    },
    G_MDSFT_COMBKEY: {
        "cmd": "gsDPSetCombineKey",
        "consts": {
            (0 << G_MDSFT_COMBKEY): "G_CK_NONE",
            (1 << G_MDSFT_COMBKEY): "G_CK_KEY",
        },
    },
    G_MDSFT_TEXTCONV: {
        "cmd": "gsDPSetTextureConvert",
        "consts": {
            (0 << G_MDSFT_TEXTCONV): "G_TC_CONV",
            (5 << G_MDSFT_TEXTCONV): "G_TC_FILTCONV",
            (6 << G_MDSFT_TEXTCONV): "G_TC_FILT",
        },
    },
    G_MDSFT_TEXTFILT: {
        "cmd": "gsDPSetTextureFilter",
        "consts": {
            (0 << G_MDSFT_TEXTFILT): "G_TF_POINT",
            (3 << G_MDSFT_TEXTFILT): "G_TF_AVERAGE",
            (2 << G_MDSFT_TEXTFILT): "G_TF_BILERP",
        },
    },
    G_MDSFT_TEXTLUT: {
        "cmd": "gsDPSetTextureLUT",
        "consts": {
            (0 << G_MDSFT_TEXTLUT): "G_TT_NONE",
            (2 << G_MDSFT_TEXTLUT): "G_TT_RGBA16",
            (3 << G_MDSFT_TEXTLUT): "G_TT_IA16",
        },
    },
    G_MDSFT_TEXTLOD: {
        "cmd": "gsDPSetTextureLOD",
        "consts": {
            (0 << G_MDSFT_TEXTLOD): "G_TL_TILE",
            (1 << G_MDSFT_TEXTLOD): "G_TL_LOD",
        },
    },
    G_MDSFT_TEXTDETAIL: {
        "cmd": "gsDPSetTextureDetail",
        "consts": {
            (0 << G_MDSFT_TEXTDETAIL): "G_TD_CLAMP",
            (1 << G_MDSFT_TEXTDETAIL): "G_TD_SHARPEN",
            (2 << G_MDSFT_TEXTDETAIL): "G_TD_DETAIL",
        },
    },
    G_MDSFT_TEXTPERSP: {
        "cmd": "gsDPSetTexturePersp",
        "consts": {
            (0 << G_MDSFT_TEXTPERSP): "G_TP_NONE",
            (1 << G_MDSFT_TEXTPERSP): "G_TP_PERSP",
        },
    },
    G_MDSFT_CYCLETYPE: {
        "cmd": "gsDPSetCycleType",
        "consts": {
            (0 << G_MDSFT_CYCLETYPE): "G_CYC_1CYCLE",
            (1 << G_MDSFT_CYCLETYPE): "G_CYC_2CYCLE",
            (2 << G_MDSFT_CYCLETYPE): "G_CYC_COPY",
            (3 << G_MDSFT_CYCLETYPE): "G_CYC_FILL",
        },
    },
    G_MDSFT_PIPELINE: {
        "cmd": "gsDPPipelineMode",
        "consts": {
            (0 << G_MDSFT_PIPELINE): "G_PM_NPRIMITIVE",
            (1 << G_MDSFT_PIPELINE): "G_PM_1PRIMITIVE",
        },
    },
}

#
# G_SETOTHERMODE_L
#

G_MDSFT_ALPHACOMPARE = 0
G_MDSFT_ZSRCSEL = 2
# G_MDSFT_RENDERMODE = 3 --- This thing has too much macros

G_SETOTHERMODE_L_SHIFTS = {
    G_MDSFT_ALPHACOMPARE: {
        "cmd": "gsDPSetAlphaCompare",
        "consts": {
            (0 << G_MDSFT_ALPHACOMPARE): "G_AC_NONE",
            (1 << G_MDSFT_ALPHACOMPARE): "G_AC_THRESHOLD",
            (3 << G_MDSFT_ALPHACOMPARE): "G_AC_DITHER",
        },
    },
    G_MDSFT_ZSRCSEL: {
        "cmd": "gsDPSetDepthSource",
        "consts": {
            (0 << G_MDSFT_ZSRCSEL): "G_ZS_PIXEL",
            (1 << G_MDSFT_ZSRCSEL): "G_ZS_PRIM",
        },
    },
    # G_MDSFT_RENDERMODE: {
    #     "cmd": "gsDPSetRenderMode",
    #     "consts": {},
    # },
}

#
# G_MOVEMEM
#

G_MV_VIEWPORT = 8
G_MV_LIGHT = 10

#
# G_MOVEWORD
#

G_MW_NUMLIGHT = 0x02
G_MW_FOG = 0x08

#
# G_MTX
#

G_MTX_PROJECTION = 0x04
G_MTX_LOAD = 0x02
G_MTX_PUSH = 0x01

G_MTX_FLAGS = {
    G_MTX_PROJECTION: "G_MTX_PROJECTION",
    G_MTX_LOAD: "G_MTX_LOAD",
    G_MTX_PUSH: "G_MTX_PUSH",
}

#
# G_GEOMETRYMODE
#

G_GEOMETRYMODE_FLAGS = {
    0x00000001: "G_ZBUFFER",
    0x00000004: "G_SHADE",
    0x00200000: "G_SHADING_SMOOTH",
    0x00000200: "G_CULL_FRONT",
    0x00000400: "G_CULL_BACK",
    0x00010000: "G_FOG",
    0x00020000: "G_LIGHTING",
    0x00040000: "G_TEXTURE_GEN",
    0x00080000: "G_TEXTURE_GEN_LINEAR",
    0x00100000: "G_LOD",
    0x00800000: "G_CLIPPING",
    0x00000800: "G_LIGHT_MAP_EXT",
    0x00004000: "G_LIGHTING_ENGINE_EXT",
    0x00000080: "G_PACKED_NORMALS_EXT",
}

#
# G_TEXTURE
#

G_ON_OFF = {
    0: "G_OFF",
    1: "G_ON",
}

G_TEXTURE_TILES = {
    7: "G_TX_LOADTILE",
    0: "G_TX_RENDERTILE",
}

#
# G_COPYMEM
#

G_COPYMEM_BODY_PARTS = {
    0: "PANTS",
    1: "SHIRT",
    2: "GLOVES",
    3: "SHOES",
    4: "HAIR",
    5: "SKIN",
    6: "CAP",
    7: "EMBLEM",
}

#
# G_SETIMG
#

G_SETIMG_FMT = {
    0: "G_IM_FMT_RGBA",
    1: "G_IM_FMT_YUV",
    2: "G_IM_FMT_CI",
    3: "G_IM_FMT_IA",
    4: "G_IM_FMT_I",
}

G_SETIMG_SIZ = {
    0: "G_IM_SIZ_4b",
    1: "G_IM_SIZ_8b",
    2: "G_IM_SIZ_16b",
    3: "G_IM_SIZ_32b",
    5: "G_IM_SIZ_DD",
}

#
# G_SETTILE
#

G_SETTILE_FMT = G_SETIMG_FMT
G_SETTILE_SIZ = G_SETIMG_SIZ
G_SETTILE_TILES = G_TEXTURE_TILES

G_SETTILE_FLAGS = {
    0x1: "G_TX_MIRROR",
    0x2: "G_TX_CLAMP",
}

#
# G_LOADTILE
#

G_LOADTILE_TILES = G_TEXTURE_TILES

#
# G_LOADBLOCK
#

G_LOADBLOCK_TILES = G_TEXTURE_TILES

#
# G_SETTILESIZE
#

G_SETTILESIZE_TILES = G_TEXTURE_TILES

#
# G_LOADTLUT
#

G_LOADTLUT_TILES = G_TEXTURE_TILES

#
# G_SETSCISSOR
#

G_SETSCISSOR_MODES = {
    0: "G_SC_NON_INTERLACE",
    3: "G_SC_ODD_INTERLACE",
    2: "G_SC_EVEN_INTERLACE",
}

#
# G_SETCOMBINE
#

G_CCMUX_COMBINED = 0
G_CCMUX_TEXEL0 = 1
G_CCMUX_TEXEL1 = 2
G_CCMUX_PRIMITIVE = 3
G_CCMUX_SHADE = 4
G_CCMUX_ENVIRONMENT = 5
G_CCMUX_1 = 6
G_CCMUX_COMBINED_ALPHA = 7
G_CCMUX_TEXEL0_ALPHA = 8
G_CCMUX_TEXEL1_ALPHA = 9
G_CCMUX_PRIMITIVE_ALPHA = 10
G_CCMUX_SHADE_ALPHA = 11
G_CCMUX_ENV_ALPHA = 12
G_CCMUX_LOD_FRACTION = 13
G_CCMUX_PRIM_LOD_FRAC = 14

G_SETCOMBINE_COLOR_COMBINERS = {
    G_CCMUX_COMBINED: "COMBINED",
    G_CCMUX_TEXEL0: "TEXEL0",
    G_CCMUX_TEXEL1: "TEXEL1",
    G_CCMUX_PRIMITIVE: "PRIMITIVE",
    G_CCMUX_SHADE: "SHADE",
    G_CCMUX_ENVIRONMENT: "ENVIRONMENT",
    G_CCMUX_1: "1",
    G_CCMUX_COMBINED_ALPHA: "COMBINED_ALPHA",
    G_CCMUX_TEXEL0_ALPHA: "TEXEL0_ALPHA",
    G_CCMUX_TEXEL1_ALPHA: "TEXEL1_ALPHA",
    G_CCMUX_PRIMITIVE_ALPHA: "PRIMITIVE_ALPHA",
    G_CCMUX_SHADE_ALPHA: "SHADE_ALPHA",
    G_CCMUX_ENV_ALPHA: "ENV_ALPHA",
    G_CCMUX_LOD_FRACTION: "LOD_FRACTION",
    G_CCMUX_PRIM_LOD_FRAC: "PRIM_LOD_FRAC",
}

G_ACMUX_COMBINED = 0
G_ACMUX_TEXEL0 = 1
G_ACMUX_TEXEL1 = 2
G_ACMUX_PRIMITIVE = 3
G_ACMUX_SHADE = 4
G_ACMUX_ENVIRONMENT = 5
G_ACMUX_1 = 6

G_SETCOMBINE_ALPHA_COMBINERS = {
    G_ACMUX_COMBINED: "COMBINED",
    G_ACMUX_TEXEL0: "TEXEL0",
    G_ACMUX_TEXEL1: "TEXEL1",
    G_ACMUX_PRIMITIVE: "PRIMITIVE",
    G_ACMUX_SHADE: "SHADE",
    G_ACMUX_ENVIRONMENT: "ENVIRONMENT",
    G_ACMUX_1: "1",
}

G_SETCOMBINE_MODES = {
    "0, 0, 0, PRIMITIVE, 0, 0, 0, PRIMITIVE":
        "G_CC_PRIMITIVE",
    "0, 0, 0, SHADE, 0, 0, 0, SHADE":
        "G_CC_SHADE",
    "TEXEL0, 0, SHADE, 0, 0, 0, 0, SHADE":
        "G_CC_MODULATEI",
    "TEXEL0, 0, SHADE, 0, 0, 0, 0, TEXEL0":
        "G_CC_MODULATEIDECALA",
    "TEXEL0, 0, SHADE, 0, 0, 0, 0, ENVIRONMENT":
        "G_CC_MODULATEIFADE",
    "G_CC_MODULATEI":
        "G_CC_MODULATERGB",
    "G_CC_MODULATEIDECALA":
        "G_CC_MODULATERGBDECALA",
    "G_CC_MODULATEIFADE":
        "G_CC_MODULATERGBFADE",
    "TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0":
        "G_CC_MODULATEIA",
    "TEXEL0, 0, SHADE, 0, TEXEL0, 0, ENVIRONMENT, 0":
        "G_CC_MODULATEIFADEA",
    "TEXEL0, 0, SHADE, 0, ENVIRONMENT, 0, TEXEL0, 0":
        "G_CC_MODULATEFADE",
    "G_CC_MODULATEIA":
        "G_CC_MODULATERGBA",
    "G_CC_MODULATEIFADEA":
        "G_CC_MODULATERGBFADEA",
    "TEXEL0, 0, PRIMITIVE, 0, 0, 0, 0, PRIMITIVE":
        "G_CC_MODULATEI_PRIM",
    "TEXEL0, 0, PRIMITIVE, 0, TEXEL0, 0, PRIMITIVE, 0":
        "G_CC_MODULATEIA_PRIM",
    "TEXEL0, 0, PRIMITIVE, 0, 0, 0, 0, TEXEL0":
        "G_CC_MODULATEIDECALA_PRIM",
    "G_CC_MODULATEI_PRIM":
        "G_CC_MODULATERGB_PRIM",
    "G_CC_MODULATEIA_PRIM":
        "G_CC_MODULATERGBA_PRIM",
    "G_CC_MODULATEIDECALA_PRIM":
        "G_CC_MODULATERGBDECALA_PRIM",
    "SHADE, 0, ENVIRONMENT, 0, SHADE, 0, ENVIRONMENT, 0":
        "G_CC_FADE",
    "TEXEL0, 0, ENVIRONMENT, 0, TEXEL0, 0, ENVIRONMENT, 0":
        "G_CC_FADEA",
    "0, 0, 0, TEXEL0, 0, 0, 0, SHADE":
        "G_CC_DECALRGB",
    "0, 0, 0, TEXEL0, 0, 0, 0, TEXEL0":
        "G_CC_DECALRGBA",
    "0, 0, 0, TEXEL0, 0, 0, 0, ENVIRONMENT":
        "G_CC_DECALFADE",
    "0, 0, 0, TEXEL0, TEXEL0, 0, ENVIRONMENT, 0":
        "G_CC_DECALFADEA",
    "ENVIRONMENT, SHADE, TEXEL0, SHADE, 0, 0, 0, SHADE":
        "G_CC_BLENDI",
    "ENVIRONMENT, SHADE, TEXEL0, SHADE, TEXEL0, 0, SHADE, 0":
        "G_CC_BLENDIA",
    "ENVIRONMENT, SHADE, TEXEL0, SHADE, 0, 0, 0, TEXEL0":
        "G_CC_BLENDIDECALA",
    "TEXEL0, SHADE, TEXEL0_ALPHA, SHADE, 0, 0, 0, SHADE":
        "G_CC_BLENDRGBA",
    "TEXEL0, SHADE, TEXEL0_ALPHA, SHADE, 0, 0, 0, TEXEL0":
        "G_CC_BLENDRGBDECALA",
    "TEXEL0, SHADE, TEXEL0_ALPHA, SHADE, 0, 0, 0, ENVIRONMENT":
        "G_CC_BLENDRGBFADEA",
    "TEXEL0, 0, TEXEL0, SHADE, 0, 0, 0, SHADE":
        "G_CC_ADDRGB",
    "TEXEL0, 0, TEXEL0, SHADE, 0, 0, 0, TEXEL0":
        "G_CC_ADDRGBDECALA",
    "TEXEL0, 0, TEXEL0, SHADE, 0, 0, 0, ENVIRONMENT":
        "G_CC_ADDRGBFADE",
    "ENVIRONMENT, 0, TEXEL0, SHADE, 0, 0, 0, SHADE":
        "G_CC_REFLECTRGB",
    "ENVIRONMENT, 0, TEXEL0, SHADE, 0, 0, 0, TEXEL0":
        "G_CC_REFLECTRGBDECALA",
    "PRIMITIVE, SHADE, TEXEL0, SHADE, 0, 0, 0, SHADE":
        "G_CC_HILITERGB",
    "PRIMITIVE, SHADE, TEXEL0, SHADE, PRIMITIVE, SHADE, TEXEL0, SHADE":
        "G_CC_HILITERGBA",
    "PRIMITIVE, SHADE, TEXEL0, SHADE, 0, 0, 0, TEXEL0":
        "G_CC_HILITERGBDECALA",
    "0, 0, 0, SHADE, 0, 0, 0, TEXEL0":
        "G_CC_SHADEDECALA",
    "0, 0, 0, SHADE, 0, 0, 0, ENVIRONMENT":
        "G_CC_SHADEFADEA",
    "PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, TEXEL0, 0, SHADE, 0":
        "G_CC_BLENDPE",
    "PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, 0, 0, 0, TEXEL0":
        "G_CC_BLENDPEDECALA",
    "ENVIRONMENT, PRIMITIVE, TEXEL0, PRIMITIVE, TEXEL0, 0, SHADE, 0":
        "_G_CC_BLENDPE",
    "ENVIRONMENT, PRIMITIVE, TEXEL0, PRIMITIVE, 0, 0, 0, TEXEL0":
        "_G_CC_BLENDPEDECALA",
    "PRIMITIVE, SHADE, TEXEL0, SHADE, 0, 0, 0, SHADE":
        "_G_CC_TWOCOLORTEX",
    "PRIMITIVE, TEXEL0, LOD_FRACTION, TEXEL0, PRIMITIVE, TEXEL0, LOD_FRACTION, TEXEL0":
        "_G_CC_SPARSEST",
    "TEXEL1, TEXEL0, PRIM_LOD_FRAC, TEXEL0, TEXEL1, TEXEL0, PRIM_LOD_FRAC, TEXEL0":
        "G_CC_TEMPLERP",
    "TEXEL1, TEXEL0, LOD_FRACTION, TEXEL0, TEXEL1, TEXEL0, LOD_FRACTION, TEXEL0":
        "G_CC_TRILERP",
    "TEXEL0, 0, TEXEL1, 0, TEXEL0, 0, TEXEL1, 0":
        "G_CC_INTERFERENCE",
    "TEXEL0, K4, K5, TEXEL0, 0, 0, 0, SHADE":
        "G_CC_1CYUV2RGB",
    "TEXEL1, K4, K5, TEXEL1, 0, 0, 0, 0":
        "G_CC_YUV2RGB",
    "0, 0, 0, COMBINED, 0, 0, 0, COMBINED":
        "G_CC_PASS2",
    "COMBINED, 0, SHADE, 0, 0, 0, 0, SHADE":
        "G_CC_MODULATEI2",
    "COMBINED, 0, SHADE, 0, COMBINED, 0, SHADE, 0":
        "G_CC_MODULATEIA2",
    "G_CC_MODULATEI2":
        "G_CC_MODULATERGB2",
    "G_CC_MODULATEIA2":
        "G_CC_MODULATERGBA2",
    "COMBINED, 0, PRIMITIVE, 0, 0, 0, 0, PRIMITIVE":
        "G_CC_MODULATEI_PRIM2",
    "COMBINED, 0, PRIMITIVE, 0, COMBINED, 0, PRIMITIVE, 0":
        "G_CC_MODULATEIA_PRIM2",
    "G_CC_MODULATEI_PRIM2":
        "G_CC_MODULATERGB_PRIM2",
    "G_CC_MODULATEIA_PRIM2":
        "G_CC_MODULATERGBA_PRIM2",
    "0, 0, 0, COMBINED, 0, 0, 0, SHADE":
        "G_CC_DECALRGB2",
    "COMBINED, SHADE, COMBINED_ALPHA, SHADE, 0, 0, 0, SHADE":
        "G_CC_DECALRGBA2",
    "ENVIRONMENT, SHADE, COMBINED, SHADE, 0, 0, 0, SHADE":
        "G_CC_BLENDI2",
    "ENVIRONMENT, SHADE, COMBINED, SHADE, COMBINED, 0, SHADE, 0":
        "G_CC_BLENDIA2",
    "TEXEL0, CENTER, SCALE, 0, 0, 0, 0, 0":
        "G_CC_CHROMA_KEY2",
    "ENVIRONMENT, COMBINED, TEXEL0, COMBINED, 0, 0, 0, SHADE":
        "G_CC_HILITERGB2",
    "ENVIRONMENT, COMBINED, TEXEL0, COMBINED, ENVIRONMENT, COMBINED, TEXEL0, COMBINED":
        "G_CC_HILITERGBA2",
    "ENVIRONMENT, COMBINED, TEXEL0, COMBINED, 0, 0, 0, TEXEL0":
        "G_CC_HILITERGBDECALA2",
    "ENVIRONMENT, COMBINED, TEXEL0, COMBINED, 0, 0, 0, COMBINED":
        "G_CC_HILITERGBPASSA2",
}
